# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

api_call <- function(url, query, value, path = "") {
    .Call(`_wibble_api_call`, url, query, value, path)
}

api_calls <- function(url, query, value, path = "") {
    .Call(`_wibble_api_calls`, url, query, value, path)
}

webble_call <- function(url) {
    .Call(`_wibble_webble_call`, url)
}

path_source <- function(path) {
    .Call(`_wibble_path_source`, path)
}

dots_example <- function(data, dots) {
    .Call(`_wibble_dots_example`, data, dots)
}

lst_tbl <- function(lst) {
    .Call(`_wibble_lst_tbl`, lst)
}

add_data <- function(data, lst) {
    .Call(`_wibble_add_data`, data, lst)
}

