# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wabble_call <- function(url, query, path = "") {
    .Call(`_wibble_wabble_call`, url, query, path)
}

api_calls <- function(url, query, value, path = "") {
    .Call(`_wibble_api_calls`, url, query, value, path)
}

webble_call <- function(url) {
    .Call(`_wibble_webble_call`, url)
}

wibble_call <- function(lst) {
    .Call(`_wibble_wibble_call`, lst)
}

path_source <- function(path) {
    .Call(`_wibble_path_source`, path)
}

dots_example <- function(data, dots) {
    .Call(`_wibble_dots_example`, data, dots)
}

add_data <- function(data, lst) {
    .Call(`_wibble_add_data`, data, lst)
}

